# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83deb413223a24f2f9f5af1d6ce355d1573c625f90a2df13f72db39b68262fb57c1ad9a661bb892567d207a94fca82664cb5ec684b7c85b622be32e4b80b591a

test:
  secret_key_base: 909f2f77db0ec532a82037b8e9f371c6bdb920de050b210997f073e9edb9866d8136543e99d5e6321b49f7354eb412f61bf501676d220e29af2e6d29024d8478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
